### ISSUE TITLE
Neue Seiten mit falschen Bereichen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#1]
Bei den neu angelegten Seiten gibt es die Bereiche "left" und "center" mit jeweils den alten CEs

**Comment by verenamaidl** [comment]
Neue Seiten werden jetzt richtig angelegt - mit Schema "Header - Main".
Gibt es eine Möglichkeit, die Seiten, die mit dem alten Schema angelegt wurden, zu ändern?

**Comment by verenamaidl** [comment]
Ich hab jetzt nach dem Löschen der "falschen" Seiten, die Seiten neu angelegt und dabei ist mir aufgefallen, dass beim anlegen einer Seite über "New" die Seiten richtig angelegt werden (also mit Header und Main), beim Anlegen über ""Create multiple pages" werden diese falschen Seiten angelegt (mit "Left" und "Center").

**Comment by leitgab** [comment]
Die `backend_layout`- und `backend_layout_next_level`-Eigenschaften werden nun mit keinem "veralteten" Default-Wert mehr versehen, sondern erben in die Information von den übergeordneten Seiten.
