### ISSUE TITLE
alte Seiten löschen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#10]
Ich würde gerne auf typo3-migration.medunigraz.at/
(fast) alle Seiten des "Originals" löschen - also (fast) alles unter PID 1 - kann ich die Rechte für rekursives Löschen haben?

**Comment by leitgab** [comment]
Im Produktiv-System keine gute Idee, aber für die Migration in den Benutzereinstellungen (rechts oben auf den Benutzernamen klicken und "User settings" öffnen") unter "Edit and advanced functions" die Checkbox "Recursive Delete(!): Allow ALL subpages to be deleted when deleting a page" aktivieren.
