### ISSUE TITLE
Such Lupe austauschen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#103]
Kannst du bitte die Lupe austauschen:
<img src="/typo3conf/ext/mug_ce/Resources/Public/css/img/icon-lupe-green.svg" alt="" class="iconsidebar">

Ich hab da leider keinen Zugriff auf dieses Verzeichnis

Und könnten wir da gleich als Alt-Text "Suche" reinschreiben?

[icon-lupe-green.zip](https://github.com/medunigraz/typo3_mug_internet_design/files/5964943/icon-lupe-green.zip)

**Comment by leitgab** [comment]
In der Seitenleiste ist nun das Icon ausgetauscht und Alt- und Title-Attribute sind gesetzt.
