### ISSUE TITLE
XSLT für Jobportal

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#104]
Ich wollt grad mit ein paar Anpassungen für den XSLT Files anfangen - bei "jobportal_A.xslt" (A für "Allgemeines") kommen die wissenschaftlichen - das ist das, was du heute mit Michael besprochen hast, oder?

Weiters ist dort  

<xsl:include href="fileadmin/XSLT/Jobportal/Locale/jobportal_DE.xslt"/> 

eingebunden. Es gibt aber gar kein Verzeichnis /Locale ??? Oder check ich da was nicht?

Wie gehen wir für diverse Anpassungen am besten vor? 
z.B. das Adaptieren der Überschriften und im CSS ein paar Änderungen vor allem bei den Abständen

**Comment by leitgab** [comment]
Die inkludierten XSL-Dateien liegen noch am alten Pfad "fileadmin/" und sollten auf das neue Storage "frontend/" umgestellt werden. Dazu müssen die Dateien auf das neue Storage kopiert werden. Im Zuge dessen sollten auch gleich die nicht mehr benötigten Dateien bei der Übernahme weggelassen werden, damit es wieder übersichtlicher wird.

**Comment by verenamaidl** [comment]
Das klappt leider nicht - ich hab jetzt im /Locale/jobportal_DE.xslt eine deutlich sichtbare Veränderung in der Schriftgröße vorgenommen und im File jobportal_Sc_Supp.xslt, der auf PID 9056 eingebunden die Referenz auf 
<xsl:include href="frontend/XSLT/Jobportal/Locale/jobportal_DE.xslt"/> 

umgestellt. Der File wird scheinbar nicht erkannt ("Content could not be loaded. Please try again later.").

Wenn man in das XSLT-CE geht, dannt steht als Info bei "Ort" 
frontend - /XSLT/jobportal/jobportal_Sc_Supp.xslt 

mit diesen Leerzeichen???

**Comment by verenamaidl** [comment]
Jetzt klappt es - wer macht das mit der Einzelansicht?

**Comment by verenamaidl** [comment]
Und wie leicht/schwer könnte man was definieren für den Fall, dass es in einer Kategorie keine Ausschreibungen gibt?
