### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#11]
es kommen bei allen möglichen CE Aktionen (neu anlegen, ändern, kopieren) SQL Fehlermeldungen 

z.B. 
An exception occurred while executing 'SELECT `mugce_add_effect` FROM `tt_content` WHERE `uid` = ?' with params [42722]: Unknown column 'mugce_add_effect' in 'field list'

	
2: SQL error: 'Unknown column 'mugce_add_effect' in 'field list'' (tt_content:NEW5f9298f4b3d84096479616)

**Comment by leitgab** [comment]
Tabellen-Update soeben durchgeführt, sollte nun funktionieren.

**Comment by verenamaidl** [comment]
Funktioniert wieder!
