### ISSUE TITLE
gleiches Submenue für "Unterseiten"

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#116]
Auf den Unterseiten eines "Subeinheit" soll überall das gleiche Submenue angezeigt werden.

Beispiel:
Das Menü in der rechten grauen Box der Seite 
https://typo3-migration.medunigraz.at/biobank
PID 8650
soll auch auf den darunterliegenden Seiten so angezeigt werden

**Comment by leitgab** [comment]
Konstante ist auf den Einstiegsseiten der Einheit zu definieren, Submenü wird angezeigt, wenn keine "Spezialkonfiguration" für den Header ausgewählt worden ist bzw. wenn "Submenü" ausgewählt ist.

**Comment by verenamaidl** [comment]
Welche Konstante und wo erfolgt der Eintrag?

Unterseiten gehen noch immer in einem eigenen Fenster auf.

**Comment by leitgab** [comment]
@verenamaidl In einem Extension-Template auf der Hauptseite der Organisationseinheit kann nun die Konstante `const.organisationNavPid` definiert werden, sodass beim Header-Typ `Plain` die Subnavigation auch auf allen Unterseiten gerendert wird.

**Comment by verenamaidl** [comment]
Ist es möglich, dass die Unterseiten von einem Menüpunkt NICHT aufgeklappt sind, wenn man auf die entsprechende Seite geht:
z.B. https://typo3-migration.medunigraz.at/rektorat/vizerektorin-fuer-forschung-und-internationales/oe-fuer-forschungsinfrastruktur/abteilung-biobank-graz/forschung
PID 8658- hier stört es nicht wirklich

Aber z.B. bei https://typo3-migration.medunigraz.at/rektorat/vizerektorin-fuer-forschung-und-internationales/oe-fuer-forschungsinfrastruktur/core-facilities/strukturbiologie
PID 9317 - hier werden das Bildelement gleich zusammengestaucht. 

Es wäre nicht unbedingt notnwendig, dass die Unterseiten aufgeklappt sind. Wenn man sie dann aufklappt und das Layout wird manchmal zusammengeschoben, wäre das okay

**Comment by leitgab** [comment]
Active-State entfernen.

**Comment by leitgab** [comment]
Submenu der Organisationseinheit hat keinen `active`-Status mehr, somit wird die Navigation nicht mehr aufgeklappt dargestellt.

**Comment by verenamaidl** [comment]
Was müsste ich bei den Konstanten eintragen, wenn ich auf einer Unterseite überhaupt KEIN Menü angezeigt haben möchte?

**Comment by leitgab** [comment]
Funktioniert `const.organisationNavPid = 0`?

**Comment by verenamaidl** [comment]
Jepp!! Perfekt! Danke!
