### ISSUE TITLE
Hero Menu ENGLISCH: falsche Formatierung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#118]
Wenn keine englischen Seiten angelegt sind, wird der entsprechende Verweis im Hero Menu anders/falsch angezeigt - das gilt auch für die Quicklinks.
Auch wenn wir wahrscheinlich von (fast) allen Seiten des Hero Menu englische Varianten anlegen, so kann doch nicht ausgeschlossen werden, dass wir einige Seiten nur auf deutsch anbieten.
Siehe Screenshot

![hero-menu-EN-20210224](https://user-images.githubusercontent.com/72002887/108972959-23019900-7684-11eb-8035-2dc27903742f.png)

**Comment by rubikon-dev** [comment]
@leitgab Bitte die Language Konfiguration so anpassen das nicht übersetze Seiten nicht angezeigt werden.

**Comment by leitgab** [comment]
Die Eigenschaft "Hide page if no translation for current language exists" wird nun standardmäßig gesetzt und bestehende Seiten habe ich wie besprochen ebenfalls darauf geändert.
