### ISSUE TITLE
Anzeige alte CEs

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#12]
es werden "immer wieder zwischendurch" zusammen mit den neuen die alten CE angezeigt - es gibt dann auch den Reiter "CAMPUSonline". Meist reicht ein Schließen und Neuaufrufen und es werden wieder nur die "normalen" CEs angezeigt
![alte-CEs](https://user-images.githubusercontent.com/72002887/97294395-3889c200-184e-11eb-98ce-9be6fa391e98.png)

**Comment by verenamaidl** [comment]
Seit ich das Ticket vorhin aufgegeben hab, hält sich dieser "Misch-Zustand" hartnäckig - ist ziemlich blöd, weil ich nicht weiß, was jetzt Rubikon-CEs sind ... 
Weder zum Altbestand noch zu den neuen Dingen gehört der Reiter "menu" mit Elementen wie "Abstracts, Categorized content ... Sitemap ..."

Wenn ich das CE Newsletter aufrufe (das Gerald angezeigt bekommt") krieg ich bei "Type" [INVALID VALUE] - kann aber dann bei Type nur die anderen CES auswählen

**Comment by leitgab** [comment]
Wie/Wo lässt sich das reproduzieren? Ich habe jetzt auf mehreren Seiten versucht ein Content Element einzufügen, aber o.g. Verhalten konnte ich dabei nicht feststellen.

**Comment by verenamaidl** [comment]
JETZT lässt sich das nicht mehr reproduzieren - jetzt ist es wieder "normal" - wobei trotzdem einige CEs fehlen dürften ... Es gibt keins für Social Media
Und es gibt noch ein witziges Phänomen, das uns keiner glauben wird: wenn ich jetzt die CEs aufrufe, dann habe ich 12 CEs unter "typical", Gerald hat dort noch das CE "Newsletter" - das eh nix kann außer ein stranges Layout zu erzeugen. Wenn ich jetzt zu Geralds Account switche habe ich dieses CE Newsletter NICHT
Ich attach jetzt einmal die CEs die ich jetzt krieg (und auch am Vormittag meistens bekommen hab .. da waren nur immer kurze Momente, wo es dieses Sammelsurium an CEs gab) 

![aktuelle--CEs](https://user-images.githubusercontent.com/72002887/97306283-8efefc80-185e-11eb-970b-36f252152a8e.png)

**Comment by verenamaidl** [comment]
Das noch zur Veranschaulichung: meine CEs und die vom Gerald - und wie oben geschrieben, wenn ich als Admin zu Geralds User wechsle, dann krieg ich "meine" Ansicht
![vgl-CE-vm-ga](https://user-images.githubusercontent.com/72002887/97308896-abe8ff00-1861-11eb-86d7-e7b4f3b0424f.png)

**Comment by leitgab** [comment]
Ich habe mir die relevaten Cache-Dateien, die das beschriebene Verhalten ggf. hervorrufen könnten, angesehen, konnte aber keinen Fehler erkennen. Auch mit Benutzerwechsel, etc. konnte ich das Problem nicht reproduzieren. Bitte um Info bzw. idealerweise einem reproduzierbaren Szenario, falls das Problem, nachdem ich die Caches geleert habe, weiterhin besteht.

**Comment by verenamaidl** [comment]
Jetzt grad schaut es gut aus ... gemma davon aus, dass es ein Cache Thema war ... mir war schon klar, dass das ein bisschen schräg daherkommt ...
