### ISSUE TITLE
API

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#121]

**Comment by leitgab** [comment]
@fladi Hab die Services News, Events und RootLine angepasst, der neue Pfad lautet `/api` statt `/api/`, die Request-Parameter sind unverändert. An Domains wird bei RootLine nur noch die Hauptdomain lt. Site-Konfiguration zurückgegeben, eventuelle Redirects sind unberücksichtigt.

**Comment by fladi** [comment]
Liefert leider nur 404 mit den Parametern die ich mitgebe:

https://www.medunigraz.at/api?tx_mugapi_endpoint%5BrecordType%5D=News&tx_mugapi_endpoint%5BrecordUid%5D=2148&tx_mugapi_endpoint%5Bredirect%5D=1#sl-content

**Comment by leitgab** [comment]
Musste noch das Mapping vom Storage-Ordner zur Detail-Page-ID anpassen - sollte jetzt funktionieren.

**Comment by fladi** [comment]
danke, funktioniert

**Comment by leitgab** [comment]
Für Events musst du weiterhin `tx_mugapi_endpoint[recordType]=Event` verwenden. Hab noch eine Anpassung vorgenommen, damit eine lesbare URL generiert wird.

**Comment by fladi** [comment]
Passt, alle URLS werden wieder korrekt generiert.
