### ISSUE TITLE
Seite für Fehler nicht gefunden

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#123]
Bitte mir zuweisen, sobald ihr die Seite angelegt habt, damit ich diese konfigurieren kann.

**Comment by verenamaidl** [comment]
PID 8179

**Comment by verenamaidl** [comment]
Ist es okay, wenn die Seiten in diesem System-Ordner liegt? Wenn nicht, bitte irgendwoanders hinschieben

**Comment by leitgab** [comment]
Wo die Seite liegt ist egal, sie muss nur erreichbar sein.
