### ISSUE TITLE
leere englische Seiten - Umleitung auf die deutsche Seite

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#125]
ist es möglich, englische Seiten, die noch keine übersetzten CEs beinhalten, auf die deutsche Seite umzuleiten?

Grund: wenn wir bei diversen Link-Listen Links auf Seiten ohne englische Inhalte haben, tut sich layoutmäßig grausiges. Wenn wir diese Links im englischen deaktivieren, müssten wir aber ans Aktivieren denken, sobald es englische Inhalte gibt ...

**Comment by leitgab** [comment]
@verenamaidl Das wollte ich gestern besprechen, habe aber darauf vergessen. Grundsätzlich wäre es schon möglich zu prüfen, ob Content Elemente auf der übersetzten Seite vorhanden sind, und falls nicht auf die deutsche Sprache weiterzuleiten. Es wäre auch möglich ein Content Fallback einzurichten, d.h. falls keine Elemente vorhanden sind, dass die Content Elemente der deutschen Sprache angezeigt werden, in diesem Fall würde man auch nicht die Sprache wechseln.

**Comment by verenamaidl** [comment]
Was ist weniger Aufwand in der Umsetzung? Da beide Lösungen für und wider haben, würde ich die weniger aufwändige nehmen.

**Comment by leitgab** [comment]
Ich hab jetzt Content Fallback konfiguriert, sodass die deutschsprachigen Inhaltselement angezeigt werden, falls diese nicht übersetzt worden sind. Bitte um Überprüfung, ob dies das gewünschte Verhalten ist.

**Comment by verenamaidl** [comment]
Perfekt!
