### ISSUE TITLE
keine Zeichenbegrenung beim Seitentitel

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#126]
das hatten wir schon erledigt, jetzt gibt es scheinbar wieder eine Zeichenbeschränkung für die Seitentitel
z.B. PID 8437
Der Seitentitel "Vizerektorin für Finanzmanagement, Recht und Digitalisierung" muss genauso stehen

**Comment by rubikon-dev** [comment]
Das ist keine Einschränkung von Seiten der CEs und auch nicht von der Extension.

**Comment by leitgab** [comment]
Wird von 255 (TYPO3-Core) auf standardmäßig 57 durch EXT:cs_seo eingeschränkt. Ich habe das Limit jetzt auf 75 erhöht und auch gleich den Seitentitel angepasst.
