### ISSUE TITLE
CE Newsletter/Anmeldung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#13]
Es sollte sowas wie ein Anmeldungs-CE geben - ich glaub, die Rubikon hat es "Newsletter" genannt - gibt es das irgendwo?

**Comment by leitgab** [comment]
Das CE "Newsletter" wurde nur für das Template "Home" freigegeben, dort steht es unter "Typical page content" zur Verfügung.

**Comment by verenamaidl** [comment]
Nein leider nicht ... soll ma wieder die Caches löschen?

**Comment by verenamaidl** [comment]
Gerald hat die Newsletter ... dafür keine Gallery und Link List

**Comment by leitgab** [comment]
Die CE "Gallery" und "Link list" sind nur in der Spalte "Content" des Page-Templates "Default" erlaubt, aber nicht auf dem Page-Template "Home". Nachfolgend die aktuell erlaubten CE in den "Content"-Spalten zur besseren Übersicht:

**Home & Default**

- Text
- Text Columns
- Text Media
- Text Media with Teaser
- Offers
- Image Tiles
- Contact
- Accordion
- Quote
- Link Button
- General Plugin

**Nur Home**

- Newsletter

**Nur Default**

- Link List
- Gallery
- Insert records

**Comment by verenamaidl** [comment]
Newsletter brauchen wir bitte auf Home & Default

**Comment by leitgab** [comment]
Es sollte jetzt möglich sein "Newsletter" auf "Default" zu verwenden.

@rubikon-dev bitte generell erlauben.

**Comment by rubikon-dev** [comment]
Wir mit dem dem nächsten Commit bei Home und Default erlaubt sein.

**Comment by verenamaidl** [comment]
Das Newsletter CE wird von uns eh nicht gebraucht 
siehe Mail von Gerald Auer, 29.10.2020, 11:09

**Comment by leitgab** [comment]
@rubikon-dev bitte des Newsletter-CE aus den erlaubten Elementen rausnehmen, sodass es nicht verwendet werden kann.
