### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#132]
Was war für die Sitemap vorgesehen?

**Comment by shaselwanter** [comment]
@verenamaidl kannst du diese Frage konkretisieren?
Sitemap kann von euch als xml generiert werden und bei google eingereicht.

**Comment by verenamaidl** [comment]
Wir wollten nur wissen, was da gedacht gewesen ist ... ist ja von euch gekommen.
