### ISSUE TITLE
Offene Stellen - Anzeige eines CE bei keinen XML Daten

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#134]
Ist es möglich, ein CE einzublenden, wenn keine Daten bei den offenen Stellen angezeigt werden?

**Comment by leitgab** [comment]
TYPO3 hat aktuell keinerlei Information bzgl. Stellen, sodass dies als Bedingung für die Ausgabe eines Content Elements nicht verwendet werden kann. Die Information ist nur bei der XSLT bekannt, dort kann bzw. wird auch schon ein entsprechender Text ausgegeben. Dieser Text kann einfach in der XSLT-Datei angepasst werden, für ein Content Element müsste man eine eigene Extension bauen.

**Comment by verenamaidl** [comment]
Alles klar! Danke
