### ISSUE TITLE
Offene Stellen - Einzelansicht

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#135]
Funktioniert bei 
https://typo3-migration.medunigraz.at/offene-stellen/wissenschaftliches-personal-aerztlich 
PID 9053

NICHT bei
9051
9054
9055
9056
9057

**Comment by leitgab** [comment]
Die URLs in den XSLT-Dateien waren noch nicht korrigiert (siehe #91), ich habe das jetzt für alle Dateien im Ordner `frontend/XSLT/jobportal/*.xslt` gemacht und hoffe nichts übersehen zu haben.

**Comment by verenamaidl** [comment]
Passen alle :)
