### ISSUE TITLE
Style Anpassungen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#137]
Die H2 von Rubikon haben alle als Klasse
<h2 class="text-bold">
definiert.

Damit alle H2 gleich ausschauen: entweder der "normalen" H2 die gleiche Attribute geben ODER bei der H2-Rubikon diese Klasse wegnehmen

**Comment by fladi** [comment]
Ich sehe leider keine Klasse hier im Issue, die wurde wohl durch die Markdown-Formatierung verschluckt. Bitte nochmal in `` posten.

**Comment by verenamaidl** [comment]
Die Rubikon H2 sind mit 
<h2 class="text-bold">
definiert
Unsere H2 haben eigentlich keine Klasse bzw. eine "leere" zugewissen: <h2 class="">

Im Prinzip könnte die Definition von <h2 class="text-bold"> als Standard für H2 genommen werden, denn wenn alle H2 die gleiche Klasse haben, ist eine Klassen-Zuteilung mMn sinnlos

**Comment by verenamaidl** [comment]
Die Rubikon-Klasse heißt class="text-bold" - die kann ersatzlos gestrichen werden.
Die allgemeine H2 soll die Definition von der Rubikon-Klasse "text-bold" haben.

**Comment by verenamaidl** [comment]
Es gibt jetzt wieder die Klasse class="text-bold hl-big" - bei H2 - die kann auch ersatzlos gestrichen werden

**Comment by verenamaidl** [comment]
H1 (ohne weitere Klassen-Spezifizierung) soll die Definitonen von 
h2 class="text-bold h1"
übernehmen!

**Comment by verenamaidl** [comment]
Druckversion ist auch nicht mehr vorhanden - die kann 1:1 vom letzten Rubikon-Stand übernommen werden

**Comment by verenamaidl** [comment]
für class="link-list" bei UL
gab es Aufzählungszeichen im Rubikon-Style - die sind verloren gegangen

**Comment by verenamaidl** [comment]
Es gabfür class="link-list" bei UL
gab es Aufzählungszeichen im Rubikon-Style - die sind verloren gegangen

Fehlt noch immer!
