### ISSUE TITLE
Umleitung auf alte Seiten

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#138]
Damit wir schon jetzt einige Themen auf die zukünftigen alten (und jetzt aktuellen) Webserver umleiten können:
Könnten wir schon jetzt festlegen, wie wir ihn nennen. **Wäre wwwcopy.medunigraz.at okay?** (Wir wollen nicht unbedingt was mit "alt", weil ja die Inhalten nicht wirklich veraltet sind).

**Comment by fladi** [comment]
Der Hostname würde www.medunigraz.at bleiben wie jetzt. Es würde gleich funktionieren, wie auch damals beim FOON-Umstieg, wir würden nur einzelen Pfade `/bla/foo/bar` oder so ähnlich an den alten Webserver umleiten. Wegen der alten TYPO3-Admin-Seite überlege ich mir noch was, da werden wir eine eigene Domain brauchen, aber die wird nur für das euer Team intern sein.

Wenn es schon eine Liste von Pfaden gibt, die wir durchschleifen sollen, dann kannst du die hier schon mal anhängen.

**Comment by verenamaidl** [comment]
Folgende Seiten bitte einmal auf den alten Server durchschalten:
Brauchst du die PIDs dazu, dann würde ich sie raussuchen

www.medunigraz.at/engip
www.medunigraz.at/lipid-hydrolysis/
www.medunigraz.at/phd-inflammatory-disorders-in-pregnancy/
www.medunigraz.at/camed/
www.medunigraz.at/kardiologie-forschung/ 
   mit allen Unterseiten:   
   www.medunigraz.at/kardiologie-forschung/forschungsgruppe-rainer/
   www.medunigraz.at/kardiologie-forschung/forschungsgruppe-myokardiale-energetik-und-metabolismus/
   www.medunigraz.at/kardiologie-forschung/forschungsgruppe-kardialer-energiesubstratstoffwechsel/
   www.medunigraz.at/kardiologie-forschung/ag-holzer/
   www.medunigraz.at/kardiologie-forschung/roc-hf/
   www.medunigraz.at/kardiologie-forschung/hcm-register/
   www.medunigraz.at/kardiologie-forschung/minotaur/
www.medunigraz.at/center-for-microbiome-research/

**Comment by verenamaidl** [comment]
Bitte diese beiden Links auf den Edis-Server weiterleiten bzw. wieder aktivieren

https://www.medunigraz.at/DK_MCD/
https://www.medunigraz.at/DK-MOLIN/

**Comment by verenamaidl** [comment]
http://www.ethikkommissionen.at/

soll auf EDIS zeigen

**Comment by fladi** [comment]
Umleitungen sind gesetzt.

**Comment by verenamaidl** [comment]
Bitte 
www.medunigraz.at/bipolar/
NICHT MEHR auf die alten Seiten durchschalten

**Comment by verenamaidl** [comment]
www.medunigraz.at/bipolar/
und
www.medunigraz.at/bipolar/idn

NICHT mehr auf den alten Server leiten

**Comment by fladi** [comment]
Beide Umleitungen wurden entfernt, für /bipolar/idn kommt nun eine 404er Fehler.

**Comment by verenamaidl** [comment]
nur /idn 
NICHT /bipolar/idn
:)

**Comment by verenamaidl** [comment]
Bitte 

www.medunigraz.at/camed/

NICHT mehr auf den alten Server leiten

**Comment by verenamaidl** [comment]
Bitte

www.medunigraz.at/camed/

NICHT mehr auf den alten Server leiten

**Comment by verenamaidl** [comment]
Bitte diese beiden Adressen WIEDER auf den EDIS-Server zeigen lassen:

- https://www.medunigraz.at/DK_MCD/
auf http://me001ned.edis.at/DK_MCD/

- https://www.medunigraz.at/DK-MOLIN/
auf http://me001ned.edis.at/DK-MOLIN/

**Comment by fladi** [comment]
https://www.medunigraz.at/DK_MCD/ und https://www.medunigraz.at/DK-MOLIN/ zeigen wieder auf EDIS.
