### ISSUE TITLE
CE News system

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#14]
Ich hab bei den Plugins ein "News system" - Gerald hat das nicht, er hat auch keinen Reiter "Special elements" mit dem Element "insert records"
![vgl-plugins-vm-ga](https://user-images.githubusercontent.com/72002887/97414629-83fea780-1904-11eb-88c4-cb7ff09adf37.png)

**Comment by leitgab** [comment]
Die Gruppe "Redakteure" darf nun auch "Insert records" verwenden. Plugins (u.a. News) würde ich für Redakteure nicht freischalten, da diese mit der Konfiguration i.d.R. überfordert sind - da würde ich eher ein CE mit der notwendigen Funktionalität bauen. Ist es überhaupt notwendig News-Elemente auf beliebigen Seiten einfügen zu können oder wird dies "vorkonfiguriert" ausgeliefert?

**Comment by leitgab** [comment]
Wie heute besprochen müsste es ein dedizierten CE für die Darstellung einer Newsliste geben, da Redakteure diese als Seiteninhalt einfügen können sollen. Es ist nicht zielführend Redakteure auf die Konfiguration des News-Plugins zu schulen.
