### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#144]
beim Speichern von Änderungen (ändern eines Links im Accordion) krieg ich 
auf PID 9262 folgenden Error:

Oops, an error occurred!
Solr HTTP error: HTTP request failed, Client error: `POST http://localhost:8983/solr/update?omitHeader=false&wt=json&json.nl=flat` resulted in a `404 Not Found` response: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </h (truncated...)

Andere “Manipulationen” (auch speichern) gehen ohne Fehler.

**Comment by leitgab** [comment]
War für mich jetzt nicht nachvollziehbar, möglicherweise war der Solr-Server kurzzeitig nicht erreichbar?

**Comment by verenamaidl** [comment]
Es war ziemlich langzeitig :) ... aber jetzt geht es wieder
