### ISSUE TITLE
Fehlermeldung statt 404

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#145]
Bei nicht existierenden URLs kommt nicht mehr die 404er Meldung sondern:

Failed to fetch error page "https://www.medunigraz.at/index.php?id=8179", reason: Client error: `GET https://www.medunigraz.at/index.php?id=8179` resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="de"> <head> <meta charset="utf-8"> <!-- This website is powered by TYPO3 - inspiring peop (truncated...)

More information regarding this error might be available
_________________________
Die Error-Seite hat die PID 8179

**Comment by leitgab** [comment]
Das ist nur temporär, bis die Domain umgestellt ist, da wir uns im Production-Context befinden und am aktuellen www die Page-ID nicht existiert.
