### ISSUE TITLE
externe URLs > eigenes Fenster

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#146]
Bei den Seiteneigenschaften - Typ "Link zu externen URLs" - diese Links gehen im gleichen Fenster auf
z.B. bei externen Quicklinks
oder PID 9589

**Comment by leitgab** [comment]
@verenamaidl Betrifft nur Verlinkungen im RTE, oder?

**Comment by verenamaidl** [comment]
@verenamaidl Betrifft nur Verlinkungen im RTE, oder?

[deine Frage kam nur per Mail und ist hier nicht zu sehen???]

Nein, es betrifft nicht den RTE, sondern wenn eine Seite als Weiterleitung auf Externe Seiten angelegt wird

**Comment by leitgab** [comment]
> @verenamaidl Betrifft nur Verlinkungen im RTE, oder?
> 
> [deine Frage kam nur per Mail und ist hier nicht zu sehen???]
> 
> Nein, es betrifft nicht den RTE, sondern wenn eine Seite als Weiterleitung auf Externe Seiten angelegt wird

Ja, habe ich hinterher bemerkt, dann habe ich meine Antwort wieder gelöscht. Schau ich mir an, wenn wir eine neue DEV-Instanz haben.

**Comment by verenamaidl** [comment]
:)
Wir warten alle gespannt!!!

**Comment by leitgab** [comment]
Institute werden `_blank` verlinkt:
https://www.medunigraz.at/forschungszentren-institute

**Comment by leitgab** [comment]
Links auf Seiten aus dem Seitenbaum sollten nun nicht mehr `_blank` verlinkt werden, selbst wenn das Link-Ziel unter einer anderen Domain erreichbar ist.
