### ISSUE TITLE
CE Social Media

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#15]
Gibt es irgendwo ein CE das sich "Social Media" nennt?

In der Mail von Silvia Haselwanter steht "Beim News Plugin gibt es jetzt den Tab "Social Media" zum Befüllen" - was könnte damit gemeint sein???

**Comment by leitgab** [comment]
Soweit ich das jetzt aus dem Code herleiten konnte, gibt es offensichtlich eine Liste von News, gefolgt von Events. Dazwischen besteht anscheinend die Möglichkeit einen "Spotlight Slider" mit der Überschrift "Spotlights" zu aktivieren, der über den Tab "Social Media" im "News"-Plugin befüllt werden kann. Zusätzlich sind im "Spotlight Slider"-Partial Links zu Social Media (Instagram, Facebook, LinkedIn und Twitter) enthalten.

Wie das Element gerendet aussehen soll, weiß ich leider nicht, aber für mich ist das rein aus dem Code heraus jetzt nicht ganz schlüssig, aber vielleicht kann da @rubikon-dev weiterhelfen.

**Comment by rubikon-dev** [comment]
Die Ansicht "List view news and events" zeigt, wie im Design festgelegt, immer 3 News, 3 Events und einen Spotlights-Slider an.
Die News und Events werden aus dem konfigurierten "Startingpoint" ausgelesen.

Zusätzlich gibt es bei der Plugin Konfiguration den Tab "Social Media" zum Befüllen der Social Media Inhalte.
Mit dem nächsten Update wird man dort auch die Überschrift definieren können.

![grafik](https://user-images.githubusercontent.com/68015247/97887039-a68c2880-1d29-11eb-88c8-e5cb29f45f34.png)

**Comment by verenamaidl** [comment]
nach wie vor ist mir nicht klar, warum wir für ein CE, dass ein Bild oder Video beinhaltet so kompliziert über das News System gehen müssen - aber ich geh auch davon aus, dass das News System nicht so bleibt 

davon unabhängig: das Design passt einfach nicht - es ist keines falls so, wie in der Mail vom 3.11.20 ("Die Headline ist so wie bei allen Elementen exakt nach Entwurf.")
Zusätzlich zur nicht korrekten Überschrift hängt im unteren Bereich ein Rest von einem grünen Strich
![social-media](https://user-images.githubusercontent.com/72002887/98241643-864bac00-1f6b-11eb-988f-8eb9c69704de.png)
