### ISSUE TITLE
Weiterleitung 

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#152]
Was müsste ich eintragen, damit 
https://pathologie.medunigraz.at/diagnostik/einsendeformulare
auf PID 8705
weitergeleitet wird.

Ich hab schon mit und ohen https versucht ...
Ist der letzte Eintrag bei den Weiterleitungen

**Comment by leitgab** [comment]
Sollte seit Freitag funktionieren.
