### ISSUE TITLE
Weiterleitung ps vs psychologie

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#153]
#^/psychologie(.*)$#
klappt nicht - das geht immer auf

https://postgraduate-school.medunigraz.at/ychologie !!!!

Es gibt halt blöderweise den Eintrag /ps der auf postgraduate-school.medunigraz.at zeigt.

Kann man "ps" mit irgendwelchen Parametern eintragen, dass es nur so genommen wird?
Oder gibt es sonst eine Lösung?

Das gleiche Problem gibt es dann natürlich auch für /psychiatrie

**Comment by leitgab** [comment]
Hab "ps" angepasst (2-3-stellige Pfade sind bzgl. Überschneidung generell problematisch).

**Comment by verenamaidl** [comment]
Danke. Eh klar, dass 2-3 Zeichen nicht so super sind, aber buuuhhh ... sag das denen, die das haben wollen
