### ISSUE TITLE
Subdomaine nicht im eigenen Fenster

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#156]
Subdomainen gehen jetzt in einem eigenen Fenster auf, am besten auf der Seite 
https://www.medunigraz.at/forschungszentren-institute
zu checken:
die Institute bzw. Lehrstühle sind jeweils Subdomaines

**Comment by leitgab** [comment]
#146

**Comment by leitgab** [comment]
Sollte behoben sein, Infos siehe in #146.
