### ISSUE TITLE
CE Umbenennung und Umordnung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#159]
Hab grad mit dem Manual für die Redakteur*innen angefangen und das wäre jetzt ein guter Anlass, bei den CEs etwas umzugestalten:
da wir falls alle CE englisch benennen, könntest du bitte folgende Umbenennungen vornehmen:

Nur Überschrift > Header only
Text & Medien > Media list
Dateilinks > File list

Wenn leicht möglich, dann bitte auch die Reihenfolge ändern:
- Dateilinks (bzw. File list) ans Ende der Aufstellung
- Text & Medien (bzw. Media list) NACH "Text Media with Teaser"

DANKE

**Comment by leitgab** [comment]
Die Elemente habe ich im Wizard und im Select umbenannt und die Reihenfolge im Select angepasst. Reihenfolge im Wizard ist etwas aufwendiger...

**Comment by verenamaidl** [comment]
Dann im Wizard so belassen - Aufwand lohnt sich da nicht!
