### ISSUE TITLE
CE News systems

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#16]
Können wir ein paar bestehende News Meldungen rüberziehen, um das News system irgendwie zu testen?

**Comment by leitgab** [comment]
@fladi Gibt es schon eine News-Konfiguration auf der neuen Seite oder ist das von Grund auf einzurichten?

**Comment by fladi** [comment]
Ich denke, wir können schon das Grundgerüst der Konfiguration übernehmen. Von der Strukturierung der Seiten wird sich ja nicht viel ändern.
