### ISSUE TITLE
CE Spotlight - Videos

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#160]
Das CE Spotlight schaut echt elegant aus, aber die eingebunden Videos zeigen keine Steuerelemente an - eigentlich checkt man gar nicht, dass es ein Video ist.
Und man kann nicht davon ausgehen, dass alle mit der rechten Maustaste drübergehen ...

Gibt es da eine Möglichkeit, Steuerelemente zu aktivieren?

Beispiel https://www.medunigraz.at/test-spotlight 
PID 9117

**Comment by leitgab** [comment]
Die Bedienelemente sind schon da, allerdings entspricht die Dimension des Videos nicht der des Spotlight-Elements, außerdem liegt die Beschreibung über dem Video (für News auf der Startseite hab ich das eh schon gefixt, aber da scheint es ein generelles Problem zu geben). D.h. das Video wird abgeschnitten und und der untere Teil überlagert.

**Comment by verenamaidl** [comment]
Ist scheinbar nicht das meistverwendete CE.
Es gibt ein Video auf 
https://biobank.medunigraz.at/
PID 8650, ID 43265

Soll ich auf PID 9117 ein paar (verschiedene) Videos einbinden?

**Comment by leitgab** [comment]
Ich habe das Spotlight-Element für Videos angepasst, damit nun das komplette Video sichtbar ist und die Beschreibung nicht die Bedienelemente überlagert. Hoffe das funktioniert so, sonst müssen wir das Element grundlegend überarbeiten, da die absolut positionierte Beschreibung immer zu Problemen führen kann/wird.
