### ISSUE TITLE
CE Text & Medien - Breite

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#163]
PID 8547
https://www.medunigraz.at/test-text-media

Ab 3 Spalten wird die Bildbreite von 200 reduziert, obwohl es sich von der Breite her gut ausgehen sollte (bei 4 Spalten sind die Bilder nur mehr 142 px breit).

Die beiden <div class="ce-textpic ce-center ce-above> und <div class="ce-gallery">
sind über 1000 px breit.

**Comment by leitgab** [comment]
Ich habe die Konfiguration angepasst, sodass nun die komplette zur Verfügung stehende Breite verwendet wird.

**Comment by verenamaidl** [comment]
Perfekt!!!
