### ISSUE TITLE
Submenue Text - HTML ermöglichen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#164]
Beim Default Header - Display Type "Text" gibt es das Feld "Teaser: Headline" (auch bei den anderen Display Types mit "Text")
- kannst du bitte in diesem Feld "Teaser:Headline" HTML zulassen, damit wir zumindest einen Link setzen können?

Bsp Header auf PID 9117

**Comment by leitgab** [comment]
Wie besprochen habe ich das Feld "Bodytext" zum Element hinzugefügt.
