### ISSUE TITLE
Events - Details - Website

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#165]
Könntest du bitte die Links bei Website einfach nur beim Wort "Website" hinterlegen ohne Anzeige des Links selbst
- analog zum "Download Program" - auch mit dem Pfeil rechts

Beispiel: https://www.medunigraz.at/events/detail/mini-med-wie-bitte-schwerhoerigkeit-heute
ID 2191

**Comment by leitgab** [comment]
Habe ich angepasst.

**Comment by verenamaidl** [comment]
Entweder jetzt wieder falsch aufgepoppt oder noch nie aufgefallen ... jetzt steht zweimal "Website" - siehe Beispiel oben oder neu etwa
https://www.medunigraz.at/events/detail/kongress-fuer-orthopaedie-traumatologie

**Comment by leitgab** [comment]
Ich denke das ist seit der Anpassung oben so - zuerst war es:
```
Website:
https://www.medunigraz.at/
```

Da der Link häufig zu lang war dies zu Umbrüchen geführt, daher die Anpassung auf:
```
Website:
Website >
```

Ich denke wir sollten bei langen Bezeichnungen - die häufig/i.d.R. zu unschönen Umbrüchen führen - generell einen Zeilenumbruch einfügen, d.h. statt aktuell:
```
Veranstalter: Med Uni Graz

Kontaktperson: 
               office@example.com

Website:
Website >
```

neu:
```
Veranstalter:
Med Uni Graz

Kontaktperson: 
office@example.com

Website:
Website >
```
Ich denke dann sieht das allgemein besser aus und die Überschrift `Website` ist nicht mehr störend bzw. folgt dem selben Schema?

**Comment by verenamaidl** [comment]
Ich glaub, es gibt ein Missverständnis - die Umstellung wegen der oft zu langen Bezeichnungen passt schon - aber es sollte nur einmal "Website" stehen - also die Überschrift weg
Es reicht, wenn nur das Website (in schwarz mit der Verlinkung) und der Pfeil bleiben

**Comment by verenamaidl** [comment]
Super - danke
