### ISSUE TITLE
Breadcrumbs 

### ISSUE THREAD

**Issue by fladi** [medunigraz/typo3_mug_internet_design#17]
Der Overflow bei den Breadcrumb-Items wird nur jeweils auf ein einzelnes Element mit einer "max-width: 30%" angewendet. D.h. wenn drei Items in der Breadcrumb diese max. Breite ausnutzen, bricht das vierte Element dann um.
Beispiel für eine solche Breadcrumb:

Med Uni Graz [NEU]
Gernot
Test 1
Lorem ipsum dolor sit amet 1
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu lectus a nulla semper dignissim. Integer viverra laoreet rutrum.
Lorem ipsum dolor sit amet 3
Lorem ipsum dolor sit amet 4

Wäre es eine Lösung, hier nur die letzten drei Eltern-Elemente in der Breadcrumb anzuzeigen, damit niemals mehr als 100% Breite entstehen kann?

**Comment by verenamaidl** [comment]
Wie schon in unserer Besprechung am 15.10.  festgelegt, die letzten 3 Ebenen für die Breadcrumb verwenden.

Laut Mail vom 4.11., 10:02, wollt ihr eine Bestätigung für die Änderung - erfolgt hiermit!!!

**Comment by verenamaidl** [comment]
Mit dem heutigen Push scheint die spaltenähnliche Darstellung zwar erledigt - aber es gibt nach wie vor 2-zeilige Breadcrumbs

Unsere Beispiele sind die gleichen wie schon beim letztenmal:

https://typo3-migration.medunigraz.at/otto-loewi-forschungszentrum/das-sind-wir/immunologie-pathophysiologie

https://typo3-migration.medunigraz.at/1/struktur-der-med-uni-graz/forschungszentren-institute/gottfried-schatz-forschungszentrum/zellbiologie-histologie-und-embryologie

https://typo3-migration.medunigraz.at/1/struktur-der-med-uni-graz/forschungszentren-institute/gottfried-schatz-forschungszentrum/das-sind-wir

**Comment by rubikon-dev** [comment]
Da der Commit von gestern ist, ist dieser Änderungswunsch leider noch nicht enthalten.
Wird mit dem nächsten Commit geliefert.

**Comment by verenamaidl** [comment]
Ist schon enthalten

**Comment by verenamaidl** [comment]
Das Rendern der Breadcrumb ist ein Standard-Feature - es ist nicht notwendig, sie verkehrt auszulesen um sie dann mittels CSS in die richtige Reihenfolge zu bringen.
U.a. ist das Float: right dann nicht mehr nötig
Gernot kann euch gerne hier einen Tipp liefern

**Comment by rubikon-dev** [comment]
Die Reihenfolge wurde umgedreht um mittels CSS die nicht gewünschten Einträge auszublenden.

**Comment by verenamaidl** [comment]
Warum wird auf der Seite https://typo3-migration.medunigraz.at/humanmedizin/mitbelegung
bei der Breadcrumb die Seite "Beratung & Information", die der Seite übergeordnet ist,  NICHT angezeigt?
![breadcrumb-mitbelegung-20210122](https://user-images.githubusercontent.com/72002887/105475553-c46d8780-5c9f-11eb-8b5b-0dca5bb39c86.png)

**Comment by rubikon-dev** [comment]
Ist es Absicht das bei dieser Seite die URL "falsch" ist?
![grafik](https://user-images.githubusercontent.com/68015247/105478438-78bcdd00-5ca3-11eb-8511-7eff8e3e2c42.png)

**Comment by leitgab** [comment]
Wenn ich das Problem auf die Schnelle richtig interpretiere: "Mitbelegung" ist im Menü verborgen, landet daher nicht zur Anzeige in der Breadcrumb-Navigation, somit ist "Beratung & Information" das letzte Element. Die Anforderung ist meines Wissens, dass die aktuelle Seite nicht in der Breadcrumb-Navigation aufscheinen soll. Lt. Umsetzung ist es aber nicht die aktuelle Seite, sondern das letzte anzeigbare Element, weshalb in diesem Fall "Beratung & Information" nicht angezeigt wird. Das Problem scheint hier die Annahme zu sein, dass das letzte Element die aktuelle Seite ist. Wahrscheinlich ist das einfach lösbar, wenn im Menü verborgene Seiten in der Breadcrumb angezeigt werden, aber ich weiß nicht, ob das gewünscht ist @verenamaidl? Sonst müsste man wohl explizit auf die Seiten-ID überprüfen...

**Comment by verenamaidl** [comment]
Es wäre sogar sehr gewünscht, wenn im Menü verborgene Seiten in der Breadcrumb angezeigt werden, denn das kommt relativ häufig vor, dass wir Seiten nicht im Submenü gelistet haben wollen, sehr wohl mit der richtigen Breadcrumb Anzeige
