### ISSUE TITLE
XSLT deutsch - englisch

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#170]
PID 9051
https://www.medunigraz.at/en/job-openings/tenure-track-professorships

Auf der englischen Seite wird immer nur der XSLT File angezeigt, der im deutschen Teil steht.
Obwohl im englischen "jobportal_Tenure_EN.xslt" eingebunden ist, wird auf beiden Seiten das DT angezeigt.

Wenn man im DT den englischen XSLT File einbindet, dann wird auf beiden Seiten die englische Variante angezeigt.

Wäre es hier okay, die "Abhängigkeit" des englischen Elements zu trennen?

**Comment by verenamaidl** [comment]
Zwei weitere Versuche:
1. Trennung der beiden XSLT-CEs - dann kommt zwar eine "Warnung" auf der Seite, dass es einen gemischten Modus gibt, und ich kann - wie vorher auch - das englische CE bearbeiten und die englische XSLT-Version anführen, aber es ändert sich in der Darstellung nichts - alles nur auf Deutsch

2. Ich habe jetzt die englische Seite neu angelegt - und die CEs nicht über "translate" sondern über "copy" erstellt - jetzt werden überhaupt alle CEs nur mehr von der deutschen Seite übernommen: der Header mit der englischen Überschrift wird nicht auf englisch dargestellt.

Gerhard hätte eine alternative Lösung - je nach URL könnte er die Aufrufe verzweigen - aber es wäre schon besser, wenn wir das in Typo3 umgesetzt bekämen - hat ja auf der alten Seite auch funktioniert.

**Comment by leitgab** [comment]
Bei übersetzten CE sollte nun die korrekte/angegebene XSL-Datei geladen werden.
