### ISSUE TITLE
Role: Redakteur/Content - Berechtigungen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#172]
Einige wenige Dinge gehen nicht wie gewünscht:

Getestet auf 
https://www.medunigraz.at/test-redakteurinnen PID 8833
__________________

CE Text Media with Teaser
- Text, Link (die letzten zwei Felder) - gehen nicht

Alle Felder, die so heißen sind sowohl bei den 
"Ausschlussfelder  - Seiteninhalt"
als auch bei "Feldwerte explizit erlauben / verbieten - Seiteninhalt Typ" aktiv 

__________________

CE Accordion
nicht im Seitenlayout - wird als erstes Element über die gesamte Breite angezeigt
https://www.medunigraz.at/test-redakteurinnen PID 8833

__________________

CE Link List
Links neu anlegen - nicht vorhanden
Bei "Feldwerte explizit erlauben / verbieten - Seiteninhalt Typ"
gibt es ein Element "Link List" - ist aktiv

**Comment by leitgab** [comment]
> CE Text Media with Teaser
> 
> * Text, Link (die letzten zwei Felder) - gehen nicht
> 
> Alle Felder, die so heißen sind sowohl bei den
> "Ausschlussfelder - Seiteninhalt"
> als auch bei "Feldwerte explizit erlauben / verbieten - Seiteninhalt Typ" aktiv

Die Feldberechtigungen für mugce_bodytext und mugce_quicklinks haben gefehlt - diese habe ich hinzugefügt.

> CE Accordion
> nicht im Seitenlayout - wird als erstes Element über die gesamte Breite angezeigt
> https://www.medunigraz.at/test-redakteurinnen PID 8833

Es handelt sich um ein "Accordion Element", da fehlt der "Accordion" Container als umschließendes Element.

> CE Link List
> Links neu anlegen - nicht vorhanden
> Bei "Feldwerte explizit erlauben / verbieten - Seiteninhalt Typ"
> gibt es ein Element "Link List" - ist aktiv

Hat sich mit der Anpassung im ersten Punkt behoben.

**Comment by verenamaidl** [comment]
Können wir auch das Hochladen/Überschreiben von Dateien über die Berechtigungen steuern? Könnten wir da demnächst einmal telefonieren?

**Comment by leitgab** [comment]
In der Benutzergruppe können unter "Mounts und Workspaces" die Berechtigungen für Ordner/Dateien festgelegt werden:
![Bildschirmfoto vom 2021-06-22 09-25-11](https://user-images.githubusercontent.com/609320/122881902-edbc3d80-d33b-11eb-84fe-a8737b0bc8c4.png)

Bin heute gut telefonisch erreichbar, morgen besser.

**Comment by verenamaidl** [comment]
Ist es okay, wenn ich "Role:basic" entsprechend ändere - das ist eh für die normalen Redakteure gedacht, oder?

Was ist der Unterschied zw. "Role: Dateiliste" und "Role:basic"- brauchen wir beides?

**Comment by leitgab** [comment]
Die "Role: Basic" ist für allgemeine Einstellungen/Freigaben gedacht, die jeder Benutzer unabhängig von weiteren Berechtigungen benötigt. Darauf aufgesetzt ist dann z.B. die "Role: Dateiliste", die den Zugriff auf das Modul "Dateiliste" und damit in Verbindung stehenden Berechtigungen hinzufügt.

**Comment by verenamaidl** [comment]
Beim CE Media List können jetzt auch die Chefredakteure keine Medien mehr hinzufügen/manipulieren - falls das nicht anders geht, dann machen wir dieses Recht für alle User wieder auf

**Comment by leitgab** [comment]
> Beim CE Media List können jetzt auch die Chefredakteure keine Medien mehr hinzufügen/manipulieren - falls das nicht anders geht, dann machen wir dieses Recht für alle User wieder auf

Da hat bei "Role: Chefredakteur/Content" noch das Feld "assets" bei den Inhaltselementen in den "excludefields" gefehlt - habe ich soeben gesetzt und sollte somit wieder möglich sein.

**Comment by leitgab** [comment]
Funktioniert alles wunschgemäß?

**Comment by verenamaidl** [comment]
Soweit einmal ja!
