### ISSUE TITLE
Role: Chefredakteur/Content - Einträge

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#173]
Beim Einrichten von Redakteur*innen bin ich jetzt über den 3. User "gestolpert", der die "Role: Chefredakteur/Content" eingetragen hat. (o_pierin, o_weber, o_ziegenfu)
Diese Personen haben nix erkennbares gemeinsam, sind auch nicht im alten Typo3 als Redakteur*innen eingetragen.

Bitte um Überprüfung, ob noch weitere diese Rolle zugeteilt haben.

**Comment by leitgab** [comment]
Die Default-User-Settings schau ich mir mit @fladi an, brauchen aber noch einen Termin.

**Comment by leitgab** [comment]
Wir hatten das irgendwann telefonisch besprochen, danach die Datenbank bereinigt, da vermutlich Altlasten vorhanden waren.
Tritt das Problem noch auf?

**Comment by verenamaidl** [comment]
Nein - tritt nicht mehr auf ... zumindest nirgends mehr (zufällig) drauf gestoßen
