### ISSUE TITLE
Role: Chefredakteur/Content - hat keine Rechte mehr CEs anzulegen ....

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#174]
Role: Chefredakteur/Content hat jetzt keine Rechte mehr CEs zu manipulieren - in der Zugriffsliste ist mMn alles aktiviert - kann das damit zusammenhängen, dass die "normalen" Redakteure diese Rechte nicht mehr haben.

Ich würde schon gerne diese Rolle für die Kolleginnen nützen und nicht allen Admin-Rechten geben

**Comment by leitgab** [comment]
Mit manipulieren meinst du löschen/hinzufügen/...?

**Comment by verenamaidl** [comment]
Ja genau! 
Role: Chefredakteur/Content hat jetzt nur den Bearbeitungsstift - sollte natürlich alles können!

**Comment by leitgab** [comment]
Soweit ich es sehe besteht das Problem nur auf PROD, aber nicht auf DEV?

Sieht mir daher nach einem Problem bzgl. Cache aus und wird schwierig nachzuvollziehen, wenn ich es auf DEV nicht reproduzieren kann...

**Comment by verenamaidl** [comment]
Ist leider kein Cache-Problem!

Ich wüsste nicht einmal die Adresse vom DEV

**Comment by verenamaidl** [comment]
Noch eine Ergänzung: Sylvia (o_trabi) hatte u.a. die Role Chefredakteur - nachdem sie gestern nur eingeschränkt arbeiten konnte, hab ich ihr Admin-Rechte gegeben - das hat aber nichts daran geändert, dass sie keine CEs löschen/hinzufügen/deaktivieren konnte.
Da hat scheinbar die Rolle Chefredakteur die Admin-Rechte beschnitten

**Comment by leitgab** [comment]
Kannst du mich diesbzgl. bitte anrufen?

**Comment by verenamaidl** [comment]
das war's! DANKE!!!!
