### ISSUE TITLE
CE Accordion - neue Elemente liegen außerhalb

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#175]
![ce-accordion-neues-element](https://user-images.githubusercontent.com/72002887/127303424-983619d2-1892-4f3f-9920-0bfb7975352f.PNG)
Wenn Redakteure neue Elemente innerhalb von einem Accordion anlegen, dann werden diese in der Preview gleich als erstes Element (unter dem Header) sowie im Accordion selbst angezeigt.
Im Backend gibt es dann
- im CE Accordion dieses neu hinzugefügte Element
- PLUS ein weiteres, "eigenes" CE vom Typ "WERT IST NICHT ERLAUBT ("mugce_accordionelement")"
  dieses Element liegt außerhalb des Seitenschemas

Ohne Freigabe auf PID 8779
Mit Freigabe auf PID 8299 
(die Freigabe gibt beides frei: www.medunigraz.at/test

**Comment by leitgab** [comment]
Die Berechtigung auf die "Spalte" hat für "Role: Redakteur/Content" gefehlt. Ich habe die Berechtigung hinzugefügt, sollte jetzt funktionieren.

**Comment by verenamaidl** [comment]
Danke - klappt!
