### ISSUE TITLE
CE Accordion - Englische Übersetzung - Unterschiede

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#176]
Wenn ich ein Accordion anlege und es übersetzte sind die Unterelemente "normal" bearbeitbar, wenn Vici eins anlegt,  fehlen sowohl die Möglichkeit die Unterelemente sichtbar zu schalten bzw. zu löschen als auch sie zu editieren 

PID 8444 
ID 60281 (ACC VZ) - von Vici angelegt - auch wenn ich die englische Übersetzung anlege, gibt es keine Bearbeitungsmöglichkeit

ID 60302 (Accordion) - geht "normal"

**Comment by leitgab** [comment]
Das Unterelement (ID 60282) im "ACC VZ" auf Englisch (ID 60306) ist das Original-Element im "ACC VZ" auf Deutsch (ID 60281), d.h. das Unterelement wurde nicht übersetzt. Sobald es eine Übersetzung des Unterelements gibt (z.B. mittels Button "Alle Datensätze lokalisieren") sollte es dann bearbeitbar sein.

**Comment by verenamaidl** [comment]
Das Element wurde eh ordnungsgemäß übersetzt - beim nächsten werd ich noch das mit dem "alle Datensätze lokalisieren" checken

**Comment by leitgab** [comment]
Habe Anpassungen am DEV-System bzw. Workflows durchgeführt, sodass nun auch die Voransicht funktionieren sollte - bitte um Abnahme.

**Comment by verenamaidl** [comment]
Ich hab ziemlich viele Bearbeitungsmöglichkeiten durchgetestet - schaut alles super richtig aus! Es funktioniert auch die Vorschau gut. Und alles auch in DT und EN!!!
Kann bitte auf PROD übernommen werden

**Comment by verenamaidl** [comment]
Oh ... ich hab grad festgestellt, dass ich das ganze nicht auf der DEV gemacht hab', sondern schon auf der PROD - das ist also eh schon überspielt - auf jeden Fall funktioniert es!!!

**Comment by verenamaidl** [comment]
Ist der Stand von der DEV jetzt gleich wie auf der PROD?

**Comment by leitgab** [comment]
Nein, die Änderungen habe ich nur auf DEV durchgeführt - zumindest die Vorschau von Accordion sollte nur auf DEV, aber nicht auf PROD funktionieren. Die Konfiguration, dass EN-Elemente funktionieren, sollte auf PROD bereits gegeben sein.

**Comment by verenamaidl** [comment]
Dann passt das eh mit unserem Testen zusammen!
Wann könntest du die Änderungen auf die PROD rübernehmen?

**Comment by leitgab** [comment]
Ich mache gleich die Git-Commits und überspiele die Änderungen auf PROD. Ich melde mich wieder, sobald erledigt.

**Comment by leitgab** [comment]
Update ist eingespielt.

**Comment by verenamaidl** [comment]
DANKE!!!!

**Comment by verenamaidl** [comment]
Oje - scheinbar werden jetzt die Elemente in den Accordions doppelt angezeigt - im Backend ganz normal einfach - aber im Frontend:
z.B.
https://zmf.medunigraz.at/merag
PID 9366

https://postgraduate-school.medunigraz.at/diagnostik-pflege-therapie/medizinische-genetik
PID 9272

**Comment by verenamaidl** [comment]
Trifft scheinbar nicht auf alle Accordions zu:
https://pharmakologie.medunigraz.at/das-sind-wir
PID 8565

**Comment by leitgab** [comment]
Hab ein Update eingespielt.

**Comment by verenamaidl** [comment]
Schaut gut aus :)
