### ISSUE TITLE
Zuordnung von zwei WS geht nicht

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#185]
Wollte bei o_wink zwei Workspaces einfügen - es geht aber nur einer - jeder für sich genommen klappt alleine.
Es "sticht" der zuerst eingetragene von den beiden WS-Einträgen (OE-df-mod-biomed und FF-mikrobiom)

User o_wellsche hat auch zwei Zuordnungen (WS-Member: OE-studium und Thema-ps) - ich bilde mir ein, da ging schon einmal beides!

**Comment by leitgab** [comment]
Wie soeben besprochen schließe ich das Issue.
