### ISSUE TITLE
Suche ENGLISCH

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#186]
1. Suche auf den englischen Seiten geht überhaupt nicht - da passiert nix, wenn man einen Suchbegriff eingibt

2. englische Seiten werden in der Suche nicht berücksichtigt.
Beispiel: Suche nach "characterize"

Da wird eine Seite gefunden, die im deutschen Zweig ist und "nur" englischen Inhalt hat, ABER die Seite https://www.medunigraz.at/en/die-universitaet-im-portraet
wo "characterize" im Zitat vorkommt, wird nicht gefunden

**Comment by leitgab** [comment]
Sollte jetzt funktionieren, die o.g. Seite befindet sich auf Suchergebnis-Seite 2.
