### ISSUE TITLE
Verwendung der Ordnerstruktur

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#19]
Wir haben heute festgestellt, dass Page-Templates im Layouts-Ordner hinterlegt worden sind - dieser ist nicht dafür gedacht!

Bitte um korrekte Verwendung der definierten TYPO3-Ordnerstruktur, siehe dafür `layoutRootPaths`, `templateRootPaths`, `partialRootPaths` in der Dokumentation von `FLUIDTEMPLATE`: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html

Ich empfehle für Page-Templates den Unterordner "Page" und für CE den Ordner "ContentElements", z.B.:
```
page.10 {
    layoutRootPaths.10 = EXT:mug_ce/Resources/Private/Layouts/Page
    templateRootPaths.10 = EXT:mug_ce/Resources/Private/Templates/Page
    partialRootPaths.10 = EXT:mug_ce/Resources/Private/Partials/Page
}
```
bzw.
```
lib.contentElement {
    layoutRootPaths.10 = EXT:mug_ce/Resources/Private/Layouts/ContentElements
    templateRootPaths.10 = EXT:mug_ce/Resources/Private/Templates/ContentElements
    partialRootPaths.10 = EXT:mug_ce/Resources/Private/Partials/ContentElements
}
```

**Comment by shaselwanter** [comment]
berücksichtigen wir zukünftig gerne.

**Comment by shaselwanter** [comment]
wie angekündigt, wird das beim nächsten commit morgen berücksichtigt
