### ISSUE TITLE
Zweisprachigkeit aktivieren

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#2]

**Comment by leitgab** [comment]
Ich habe Englisch als Zweitsprache aktiviert, d.h. Elemente können im Backend übersetzt werden.

Im Frontend muss der Sprachumschalter entsprechend adaptiert werden.

**Comment by rubikon-dev** [comment]
Der Sprachschalter im Frontend sollte eigentlich funktionieren.

https://typo3-migration.medunigraz.at/test-language

**Comment by fladi** [comment]
@verenamaidl Ist hier noch etwas zu tun?

**Comment by verenamaidl** [comment]
Scheint zu klappen - die "Translate" Funktion ist mit der neuen Typo3 Version auch etwas umfangreicher  :)
