### ISSUE TITLE
MEDonline-Visitenkarten URL für Personensuche

### ISSUE THREAD

**Issue by fladi** [medunigraz/typo3_mug_internet_design#20]
Die Suchtreffer für Personen sollen auf die MEDonline-Visitenkarte verlinken. Dafür muss in `EXT:campusonline` die Person-Domain um ein Feld `URL` erweitert werden. Für den Import muss der Wert für dieses Feld das aus der View `LOC_WEB_PUBLIC.PERSONEN` bezogen werden. Dieses Feld wird noch angelegt und enthält dann die absolute URL zur Visitenkarte.

**Comment by fladi** [comment]
Das Feld in der View ist nun verfügbar und trägt den Namen `VISITENKARTE`.

**Comment by leitgab** [comment]
Es wird nun die API statt der DB-Verbindung verwendet, darüber stehen aber nicht alle Felder zur Verfügung, sehr wahrscheinlich sind diese auch nicht erforderlich, aber sollten wir durchgehen. Das Feld Visitenkarte müsste aber via API bereitgestellt werden.

**Comment by leitgab** [comment]
@fladi Wir haben heute die Felder durchbesprochen, die API müsste bitte um folgende Felder ergänzt werden:

**OU**
- Homepage (war: WWW)
- Fax (war: FAX)
- Sekretariat (war: SEK)

**Person**
- Telefonnummern (war: TELEFON_NUMMER/MOBILTELEFON_NUMMER/INTERNE_TELEFON_NUMMER)
- Fax (war: FAX)
- Visitenkarte (war: VISITENKARTE)

**Comment by fladi** [comment]
@leitgab OK, kläre ich mit MEDonline ab, damit wir die Felder bekommen. Die Visitenkarten-URL ist ja auf der TestAPI schon verfügbar oder ist damit etwasd anderes gemeint?

**Comment by leitgab** [comment]
@fladi Visitenkarte (neu: card) ist auf der TestAPI erledigt.

**Comment by fladi** [comment]
Die fehlenden Felder sind nun in der Test-API verfügbar:

https://api-test.medunigraz.at/v1/campusonline/organization/
https://api-test.medunigraz.at/v1/campusonline/person/

**Comment by leitgab** [comment]
Ausgabe der Visitenkarten-URL in der Suche passt noch nicht.
