### ISSUE TITLE
News System

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#25]
Gernot, am 29.10.20:
Wie heute besprochen müsste es ein dedizierten CE für die Darstellung einer Newsliste geben, da Redakteure diese als Seiteninhalt einfügen können sollen. Es ist nicht zielführend Redakteure auf die Konfiguration des News-Plugins zu schulen.

Bitte um eine entsprechende Lösung für das News System

**Comment by verenamaidl** [comment]
Design ist auch nicht ganz dem Entwurf gemäß ...
Bsp: https://typo3-migration.medunigraz.at/test-ce-final
![ce-news-system-bsp-kategorie](https://user-images.githubusercontent.com/72002887/98244532-e5abbb00-1f6f-11eb-8018-2a4f5bdc0163.png)

**Comment by rubikon-dev** [comment]
Bei den News sind nur folgende Views umgesetzt, da auch nur diese im Design vorhanden sind.
- List view
- Detail view
- List view news and events

Die übrigen Views sollen nicht zur Auswahl angeboten werden.
Können mit TCEFORM.tt_content.pi_flexform.news_pi1.sDEF.switchableControllerActions.removeItems entfernt werden

**Comment by leitgab** [comment]
Soeben mit @verenamaidl besprochen: Ein separates Content Element für nur News und nur Events wird nicht benötigt. Die aktuell verfügbaren Varianten sind ausreichend.
