### ISSUE TITLE
Spiegeln von CE

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#3]
"Insert records" für den Content Bereich aktivieren.

Test am 5.10. 
Text-Element klappen problemlos 
Bei den "zusammengesetzten CE" scheint es aber Probleme zu geben: zB CE 42097 (Offers Kunst am Campus) von PID 8407 wurde auf der Seite Leben am Campus (8408) ganz unten eingefügt - es wird aber nur die Überschrift angezeigt.

**Comment by leitgab** [comment]
Hab jetzt nicht alle Elemente durchgesehen, aber grundsätzlich ist das Problem, dass `pidInList = this` gesetzt ist, weshalb die verknüpften Elemente auf die aktuelle Seite beschränkt werden, das könnte mit `pidInList = 0` wohl gelöst werden, da die Einschränkung der verknüpften Elemente ohnehin anhand der `uid` erfolgt.

**Comment by rubikon-dev** [comment]
Grundsätzlich sollte ja beim Kopieren die richtige pid gesetzt werden aber wir können im dataProcessing die Bedingung pidInList auch raus nehmen. Hat wahrscheinlich den gleichen Effekt (pidInList = 0 haut leider nicht hin). Wir werden das mit dem nächsten Commit pushen.

**Comment by verenamaidl** [comment]
Da hat sich leider noch überhaupt nix getan ... das Spiegeln der "einfachen" Elemente geht, aber die "zusammengesetzten" CEs klappen nach wie vor nicht. 
Beispiele auf PID 8548

**Comment by leitgab** [comment]
Es muss `pidInList.field = pid` gesetzt werden, damit es funktioniert: @rubikon-dev bitte bei den CE mit `DatabaseQueryProcessor` nachkonfigurieren. Danke!

**Comment by leitgab** [comment]
@verenamaidl Funktioniert es jetzt?

**Comment by verenamaidl** [comment]
Schönen guten Morgen,

jepp – großartig!!!!

Danke und lieben Gruß
Verena


Von: leitgab <notifications@github.com>
Gesendet: Montag, 16. November 2020 12:09
An: medunigraz/typo3_mug_internet_design <typo3_mug_internet_design@noreply.github.com>
Cc: Maidl, Verena <verena.maidl@medunigraz.at>; Assign <assign@noreply.github.com>
Betreff: Re: [medunigraz/typo3_mug_internet_design] Spiegeln von CE (#3)


@verenamaidl<https://github.com/verenamaidl> Funktioniert es jetzt?
