### ISSUE TITLE
CE Text Media with Teaser - keine grauer Hintergrund | falscher grüner Strich | zu geringer Abstand

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#32]
Möglichkeit,   den grauen Hintergrund zu deaktivieren

Sollte laut Mail vom 3.11.20 erledigt sein

- ist nicht so - es gibt zwar den Display Type "no background" - aber der wirkt sich nicht aus

![ce-text-media-with-teaser](https://user-images.githubusercontent.com/72002887/98243618-7b464b00-1f6e-11eb-948f-7d01b55dcc80.png)

**Comment by verenamaidl** [comment]
Am vorigen Screenshot ist auch eindeutig zu erkennen, dass der Abstand zum nächsten CE zu klein ist!!!!

Und es hängt ein grüner Strich unmotiviert im Bild

**Comment by rubikon-dev** [comment]
Da ist leider beim internen Merge was verloren gegangen und war damit nicht Commit enthalten.
Wir in der nächsten Stunde noch nachgeliefert.

Der grüne Strich ist Teil des nächsten (News System) Element und dieses ist nach oben verschoben da keine News bzw. Events konfiguriert sind. Das wurde nicht berücksichtigt da es kein Anwendungsfall sein sollte. Sollen wir da ein neues Issue dazu anlegen?

**Comment by shaselwanter** [comment]
@verenamaidl wurde bereits gepusht

**Comment by verenamaidl** [comment]
Hintergrund und grüner Strich erledigt,
Nues Issue dann im Bedarfsfall- prinzipiell sollte schon jedes CE nach/vor jedem kombinierbar sein.
