### ISSUE TITLE
CE Offers | Überschriften   bei den einzelnen Elementen: NICHT als Pflichtfeld

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#36]
mit Push vom 4.11.20 erledigt

ABER: der Strich, der unter der Überschrift angezeigt wird, soll natürlich auch NICHT angezeigt werden 

Der Text soll dann oben bündig mit dem Bild beginnen

![ce-offers-ohne-headline](https://user-images.githubusercontent.com/72002887/98246903-383aa680-1f73-11eb-80e6-a415ef660bf5.png)

**Comment by rubikon-dev** [comment]
Da ist leider beim internen Merge was verloren gegangen und war damit nicht im Commit enthalten.
Wird in der nächsten Stunde noch nachgeliefert.

Siehe auch Issue #32.

**Comment by shaselwanter** [comment]
@verenamaidl ist bereits gepusht worden

**Comment by verenamaidl** [comment]
Den Strich gibt es noch immer

**Comment by verenamaidl** [comment]
grauer HG noch immer nicht deaktivierbar, Abstand noch immer zu gering
siehe auch z.B. https://typo3-migration.medunigraz.at/bsp-3
