### ISSUE TITLE
Textformatierung <UL> List mit Pfeilen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#44]
Textformatierung   <UL> List mit Pfeilen

Rubikon, 3.11.20
Wurde bereits beim letzten mal umgesetzt http://meduni.rubikon-web25.at/die-universitaet/die-universitaet-sub5/die-universitaet-subsub-1

Bei uns noch NICHT sichtbar

![linkliste](https://user-images.githubusercontent.com/72002887/98250095-53a7b080-1f77-11eb-95b0-406517fafaa2.png)

**Comment by rubikon-dev** [comment]
Die Einträge in der Liste müssen Links sein damit auch die Pfeile kommen. So war es ursprünglich ja auch ausgemacht.
Bitte testen ob das so brauchbar ist wie wir das damals besprochen haben.

**Comment by verenamaidl** [comment]
Nein, es war ausgemacht, dass sie in einem Textfeld verwendet werden können. Da es ist im Editor verfügbar ist, geh ich davon aus, dass ich sie entsprechend verwenden kann

**Comment by rubikon-dev** [comment]
Pfeile können auch in einem Textfeld verwendet werden und sie sind auch im Editor verfügbar. Der Pfeil selbst erscheint, sobald das li ein Link ist. Siehe auch Screenshots,
Laut unserem Protokoll vom Meeting war der Wunsch, es so umzusetzen, damit der Redakteur das gut nutzen kann. Natürlich können wir das abändern und den Pfeil auch anzeigen, wenn kein Link vorhanden ist. Das wird den Besucher der Seite vermutlich aber irritieren, wenn Pfeile nur hin und wieder Links sind.

![grafik](https://user-images.githubusercontent.com/68015247/98254108-2b6e8080-1f7c-11eb-9856-6027b0869f15.png)
![grafik](https://user-images.githubusercontent.com/68015247/98254143-37f2d900-1f7c-11eb-8d60-4f03c9f65bac.png)
