### ISSUE TITLE
Default-Layout für CE verwenden

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#45]
Bitte für die Custom-CE das Default-Layout verwenden, das im Core in EXT:fluid_styled_content verwendet wird, damit die Core-Funktionalitäten zur Verfügung stehen (z.B. Sprungmarken für übersetzte CE) - nachfolgend das Template für Generic-CE: https://github.com/TYPO3/TYPO3.CMS/blob/9.5/typo3/sysext/fluid_styled_content/Resources/Private/Templates/Generic.html

**Comment by shaselwanter** [comment]
@leitgab wird mit dem nächsten commit (morgen) mitgeliefert
