### ISSUE TITLE
Einheitlichkeit

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#46]
Letzte Woche ist uns beim Arbeiten aufgefallen, dass manche Elemente auf unterschiedliche Varianten umgesetzt worden sind, z.B. wird die Breadcrumb teilweise beim Header Content-Element, teilweise im Template gerendet. Selbiges gilt in ähnlicher Weise für die "greenbox". Wäre es möglich dies anzugleichen oder gibt es einen sinnvollen Grund, warum das nicht gleich ist?

**Comment by rubikon-dev** [comment]
Die Breadcrumbs gehören aus unserer Sicht eigentlich zum Template. Da der Default Header aber auch einen Teil des Inhaltes (die H2) rendert, und die Breadcrumb Navigation damit Teil des Elements ist,  ist das bei diesem Element nicht leicht möglich bzw. würde das HTML und damit das Styling unnötig kompliziert und unübersichtlich machen. D.h. wir könnten das Breadcrumb nur generell in die Header schieben was uns aber nicht korrekt erscheint.

**Comment by leitgab** [comment]
Im Sinne der Wartbarkeit wären einheitliche Lösungen von Vorteil gewesen, sodass bei Anpassungen nicht Korrekturen an mehreren Stellen vorgenommen werden müssen. In Hinblick auf den Projektfortschritt und um nicht wieder Komponenten aufgrund von Änderungen kaputt zu machen, wollen wir es dabei belassen, schließlich ist uns bei der Wartung bewusst, worauf wir achten müssen.
