### ISSUE TITLE
HTML Tabellen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#52]
Können wir die bestehenden HTML-Tabellen-Stile (grau, grün, weiß) übernehmen bzw. dann auch noch ev. ein/zwei neue dazugeben?

**Comment by leitgab** [comment]
Grundsätzlich ja, aber es muss auch vom CSS unterstützt werden. Ich denke wir sollten die verfügbaren Tabellenstile festlegen und im RTE auswählbar machen, anschließend die Rubikon das CSS abhängig vom generierten HTML erweitern.

@verenamaidl: Welche Tabellen-Stile sollen im RTE zur Verfügung stehen?

**Comment by verenamaidl** [comment]
Können wir da als Basis gleich die bestehenden nehmen?

**Comment by verenamaidl** [comment]
Könntest du bitte - unabhängig von den alten Tabellen - folgende 4 Tabellenformate definieren:

table.linien, th.linien, td.linien, caption.linien {
  border: 1px solid #eee; padding: 5px; 
}
________________________________
table.gruen, td.gruen, caption.gruen {
  border: 1px solid #007934; padding: 5px; 
}   
th.gruen   {
  border: 1px solid #007934; background: #007934; color: #fff; padding: 5px; 
}   
________________________________
table.grau {padding: 5px;
}
th.grau, td.grau, caption.grau {
  border: 3px solid #fff; padding: 5px; background: #eee;
}
________________________________
table.zebra, th.zebra, td.zebra, caption.zebra {
  border: 3px solid #fff; padding: 5px; 
}
table.zebra tr:nth-child(even) { 
  background-color: #eee; 
  color: #000; 
} 

___________________
Sollten in etwa so dann ausschauen: http://me001ned.edis.at/tabellen-formate.html

Hoffe, du hast das mit den Definitionen so gemeint ... sonst bitte melden!

**Comment by leitgab** [comment]
Die Tabellen-Styles sind im RTE konfiguriert und führen zu folgenden Bootstrap-CSS-Standard-Klassen für Tabellen:
- .table.table-bordered (alt: .linien)
- .table.table-primary (alt: .gruen)
- .table.table-secondary (alt: .grau)
- .table.table-striped (alt: .zebra)

@rubikon-dev Bitte die oben von @verenamaidl genannten Styles für die hier genannten CSS-Klassen hinterlegen.
