### ISSUE TITLE
CE Contact - Titles | Zeichen hochstellen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#53]
In den beiden Title-Feldern des CE Contact müssen Zeichen hochgestellt werden können, z.B. für Dr.in

**Comment by verenamaidl** [comment]
Der Punkt nach Mag. und Dr. muss bleiben - also: Mag.a bzw. Dr.in (a und in hochgestellt)

**Comment by verenamaidl** [comment]
Wo KEIN Punkt ist, darf aber nicht ein Punkt angezeigt werden!!! 
Nicht bei jedem "in" kommt davor ein Punkt (z.B. PDin oder DIin)
Die Regel, dass hochgestellt wird, sollte sich nur auf "a" und "in" beziehen.

**Comment by rubikon-dev** [comment]
Die Syntax fürs Hochstellen haben wir mit **.a** bzw. **.in** festgelegt.
D.h. Dr.in wird das in hochgestellt, bei PDin nicht. 
Jedes "in" und "a" (ohne Kennzeichnung) hochzustellen würde zu falschen Ergebnissen führen.

Was wir machen können ist:
**.a** bzw. **.in** wieder wie ursprünglich in **<sup>a</sup>** bzw. **<sup>in</sup>** ohne Punkt umzuwandeln und dann wie folgt verwenden:
- Dr..in => Dr.<sup>in</sup>
- PD.in => PD<sup>in<sup>
- ...

**Comment by verenamaidl** [comment]
Die Eingabe soll syntaktisch immer korrekt erfolgen.
Bitte einfach die für Zeichenfolge PDin und DIin die entsprechende Regel eintragen.
