### ISSUE TITLE
alte CEs ins neue Typo3 übernehmen

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#55]
Bitte folgende CEs vom jetzigen Typo3 fürs neue übernehmen:

- Nur Überschrift
- Text & Medien
- Reines HTML
- Plugin XSLT
- Openstreetmap

**Comment by leitgab** [comment]
Folgende Content Elemente und Plugins können nun beim Default-Backend Layout im Content verwendet werden:
- Nur Überschrift
- Text & Medien
- Reines HTML
- Openstreetmap

Ggf. sind Template-/Style-Anpassungen erforderlich.

Das Plugin für das XSLT-Rendering wird in #57 erledigt.

**Comment by verenamaidl** [comment]
Danke!!!
Die CEs passt die Positionierung nicht - ist das Sache der Rubikon, dass alle CEs, die im Bereich Main eingefügt werden, entsprechend angezeigt werden?

**Comment by verenamaidl** [comment]
https://typo3-migration.medunigraz.at/bsp-3

**Comment by leitgab** [comment]
Habe das Verhalten gestern mit @fladi besprochen und ein Issue #58 dafür erstellt.

**Comment by verenamaidl** [comment]
Merci!!!




Von: leitgab <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 08:01
An: medunigraz/typo3_mug_internet_design <typo3_mug_internet_design@noreply.github.com>
Cc: Maidl, Verena <verena.maidl@medunigraz.at>; Assign <assign@noreply.github.com>
Betreff: Re: [medunigraz/typo3_mug_internet_design] alte CEs ins neue Typo3 übernehmen (#55)


Habe das Verhalten gestern mit @fladi<https://github.com/fladi> besprochen und ein Issue #58<https://github.com/medunigraz/typo3_mug_internet_design/issues/58> dafür erstellt.

**Comment by leitgab** [comment]
Ich habe noch eine Korrektur vorgenommen (siehe #58 bzw. baf2057), sodass nun sämtliche Elemente im Container positioniert sein sollten.

**Comment by verenamaidl** [comment]
Schaut gut aus!!! Kömma schließen, oder?
