### ISSUE TITLE
XML/XSLT-Plugin

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#59]

**Comment by leitgab** [comment]
@verenamaidl hatte leider kein XML/XSL bei der Hand, um es ausprobieren zu können. CE steht jetzt zur Verfügung.

**Comment by verenamaidl** [comment]
https://typo3-migration.medunigraz.at/test-dezember

klappt - CE wird halt außerhalb des Containers angezeigt, aber das ist ja eine andere Baustelle ...

**Comment by verenamaidl** [comment]
Könntest du das CE noch in den Reiter ""Special elements" rüberschieben?

hab einmal 2 der alten XSLT übernommen

**Comment by verenamaidl** [comment]
https://typo3-migration.medunigraz.at/offene-stellen/allgemeines-universitaetspersonal

klappt auch ... Layout lässt halt noch zu wünschen über ..

**Comment by leitgab** [comment]
Das XSLT-Content Element ist nun im Reiter "Special elements" eingeordnet.

Der fehlende Container wird mit #58 gelöst.
