### ISSUE TITLE
alte CE werden über LIST auf den neuen Seiten angelegt

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#6]
auf allen neu angelegten Seiten werden über 27.000 alte CE aufgelistet

**Comment by leitgab** [comment]
Hier werden die Query-Constraints aus dem TYPO3-Core überschrieben und somit u.a. die Einschränkung auf die Seiten-ID.
https://github.com/medunigraz/typo3_mug_internet_design/blob/8fc7093f18324dff00e2fc021d857ef0c1301ffa/Classes/Hooks/Backend/RecordListQueryHook.php#L21
Mit `addWhere()` statt `where()` kann das Problem behoben werden.

**Comment by rubikon-dev** [comment]
Da ist wahrscheinlich andWhere gemeint.
Wird mit dem nächsten Commit behoben.

**Comment by leitgab** [comment]
> Da ist wahrscheinlich andWhere gemeint.
> Wird mit dem nächsten Commit behoben.
Ja, natürlich.

**Comment by leitgab** [comment]
@verenamaidl funktioniert das jetzt?

**Comment by verenamaidl** [comment]
Ja - jetzt alles korrekt unter LIST
