### ISSUE TITLE
CE tiles | Headline Kicker | unten  bünding

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#66]
Die Text-Elemente beim CE Tiles müssen unten bündig sein - damit z.B. bei 2-zeiliger Headline Kicker oder auch 2-zeiliger Headline der Strich noch zu sehen ist.

Beispiel: 
https://typo3-migration.medunigraz.at/test-dezember?

**Comment by verenamaidl** [comment]
Ist nach wie vor nicht unten bündig

**Comment by rubikon-dev** [comment]
Da hatten wir leider mit unserem internen Git Probleme und der Fix wurde nicht übernommen. Wird mit dem nächsten Commit geliefert.
