### ISSUE TITLE
Bootstrap Primärfarbe anpassen

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#67]
Die Primärfarbe wurde in Bootstrap nicht auf das Med Uni-Grün geändert, d.h. wird bei vielen Standardelementen (Button/Pagination) die Bootstrap-Standardfarbe verwendet.

**Comment by fladi** [comment]
Ich habe nun für die Pagination schon die Colormap von Bootstrap in SCSS anpassen müssen. Die Primärfarbe ist nun schon mal in meinem Branch gesetzt: 691b8e5a8b9d0515bf599bc3711843c5a3edc977
