### ISSUE TITLE
Hero-Menu liegt über dem Content

### ISSUE THREAD

**Issue by leitgab** [medunigraz/typo3_mug_internet_design#68]
Wenn kein Header-Bild eingefügt wird und somit der Inhalt ganz oben (direkt unter dem Header) beginnt, liegt das Hero-Menü über dem Content. Der Text oder ein eventuelles Formular sind daher nicht selektierbar.

**Comment by rubikon-dev** [comment]
@leitgab Bitte um Info welche Seite(n) betroffen sind bzw. um eine Beispielseite.
https://typo3-migration.medunigraz.at/gernot/test-5 ist z.B. ein Seite ohne Header und aus unserer Sicht ok.

**Comment by leitgab** [comment]
![Bildschirmfoto vom 2021-01-20 12-32-17](https://user-images.githubusercontent.com/609320/105169294-9f500c00-5b1b-11eb-93e4-2d5fc1c69b59.png)

**Comment by rubikon-dev** [comment]
Wurde der durch den "neuen" Abstand und Issue #58 gefixt. Leider haben wir kein Beispiel mehr.

**Comment by leitgab** [comment]
Es wurde jetzt nur der Content nach unten verschoben, `padding: 0 0 70px 0;` auf `.main-menu .hero-menu` ist nach wie vor vorhanden. Ist das aus irgendeinem Grund notwendig oder kann es einfach entfernt werden?

**Comment by rubikon-dev** [comment]
Padding wird nicht mehr benötigt und wurde entfernt.
