### ISSUE TITLE
Rechte für Redakteure - KEINE neuen CEs | kein URL Generierung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#7]
Zwei Probleme bei Gerald, Vici oder Sylvia 

- die neuen CE stehen ihnen nicht zur Verfügung

- beim Anlegen einer neuen Seite anlegen, wird keine URL  generiert - ich hab bis jetzt dann immer das URL Segment aktiviert - ist natürlich keine Dauerlösung

**Comment by leitgab** [comment]
Die BE-Gruppe "Redakteur" wurde auf die neuen CE und das "Slug"-Feld der Seite berechtigt.

**Comment by leitgab** [comment]
Ich habe die Berechtigung für die neuen CE "Simple Header" und "Link Button" hinzugefügt.
