### ISSUE TITLE
Öffnen von referenzierten Dateien in neuem Fenster 

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#71]
soweit ich mich erinnern kann, war das schon richtig definiert

z.B. für  https://typo3-migration.medunigraz.at/dokumente/vollmachten

**Comment by leitgab** [comment]
Verlinkungen auf Dateien sollten nun standardmäßig mit `target="_blank"` erfolgen.

@verenamaidl Bitte überprüfen, ob es erwartungsgemäß funktioniert und nicht auch andere Verlinkungen betroffen sind.

**Comment by verenamaidl** [comment]
Im Editor klappt es.
Beim CE Link Button muss es noch nachgezogen werden.
z.B. PID 8431
https://typo3-migration.medunigraz.at/humanmedizin/zielsetzung-studienplan

**Comment by leitgab** [comment]
Jetzt sollten alle Dateilinks berücksichtigt sein.

**Comment by verenamaidl** [comment]
Dateien gehen leider wieder im gleichen Fenster auf ... bitte bei Gelegenheit nachziehen. Danke

**Comment by leitgab** [comment]
Hab offensichtlich irgendwann versehentlich ein paar kleinere Anpassungen, die noch nicht commited waren, überschrieben. Sollte jetzt wieder passen.

**Comment by verenamaidl** [comment]
Alles kein Problem ... solange es du lösen kannst :)
