### ISSUE TITLE
CE Offers - Bilder zu klein dargestellt

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#73]
Bei neu angelegte CE Offers werden die Bilder verkleinert dargestellt

auf der Seite PID 8548
https://typo3-migration.medunigraz.at/gernot/test-6

liegt ein altes CE Offers und darüber ein neu angelegtes

**Comment by leitgab** [comment]
@rubikon-dev Die Bildgröße ist abhängig von der Textlänge, siehe "TEST NEUES ELEMENT". Ist die Länge des Textes kürzer als die Zeile, werden die beiden "Zellen" nicht auf die volle Breite gestreckt. Lässt sich z.B. mit `.ce-offers .ce-offer { width: 100%; }` beheben.
