### ISSUE TITLE
Shortcut zu Anker möglich?

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#75]
Wir bräuchten bei den Quicklinks Karriere - Arbeitsumfeld -  Interessensvertretungen PID 9150
eine Verlinkung auf die Seite https://typo3-migration.medunigraz.at/struktur PID 8420 auf das CE 42453 (unten Interessensvertretungen).
Ist das irgendwie möglich?

**Comment by leitgab** [comment]
Das ist nur mit einer [Extension](https://github.com/lochmueller/custom_shortcut) oder als externe URL möglich. Würde aber zur externen URL raten, da Core.

**Comment by verenamaidl** [comment]
Ah - da hätt ich natürlich auch selbst drauf kommen können ... Merci für den Tipp!
