### ISSUE TITLE
Link Label im CE Text

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#77]
Bei den Links im CE Text (und auch in den anderen CEs, die die Links rechtsbündig mit Pfeil anzeigen): 
Der Pfeil soll bei Mehrzeiligkeit rechts vom rechtsbündigen Text stehen und nicht unter dem Text der oberen Zeile

Beispiel: https://typo3-migration.medunigraz.at/beratung-kontakt/medonline

**Comment by verenamaidl** [comment]
Das ist noch immer gleich

**Comment by rubikon-dev** [comment]
Da hatten wir leider mit unserem internen Git Probleme und der Fix wurde nicht übernommen. Wird mit dem nächsten Commit geliefert.
