### ISSUE TITLE
Fehlermeldung beim Anlegen der englischen Seite

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#85]
Gerald hat bei 2 Seiten versucht, die englische Version anzulegen und hat eine Fehlermeldung bekommen, die ich auch bekomme, wenn ich auf "Make new translation ..." gehe. Bei allen anderen Seiten ging es ganz normal.
Die beiden Seiten sind:
Diversität & Barrierefreiheit PID 8412
Familie & Universität PID 8413

Die Fehlermeldung lautet:
![fehlermeldung-en-translation](https://user-images.githubusercontent.com/72002887/105692218-6db1b900-5efe-11eb-9a99-14831815cfb6.jpg)

**Comment by leitgab** [comment]
Der Gruppe `Redakteur` hatte die Berechtigung auf das Feld `l10n_parent` gefehlt. Ich habe jetzt die Berechtigung hinzugefügt und die "fehlerhaften" Datenbank-Einträge korrigiert.
