### ISSUE TITLE
CE insert records - bei Offers fehlt der graue Randbereich

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#87]
Auf 
https://typo3-migration.medunigraz.at/test-gespiegelte-elemente   PID 8324
sind 2 gespiegelte Offers - einmal mit (Standard), einmal ohne den grauen Hintergrund (Display Type no background)

Originale liegen auf
https://typo3-migration.medunigraz.at/test-ces
PID 8222

beim grauen gespiegelten Offers wird der graue Bereich links und rechts nicht angezeigt

Und bei dieser Gelegenheit: WIE find ich heraus, auf welcher Seite ein Original-CE liegt? Gibt es eine Suchfunktion für die CE-IDs?

**Comment by leitgab** [comment]
Es wird nun beim Shortcut kein Container mehr eingefügt, sodass das referenzierte Elemente im Original angezeigt wird.

Im Shortcut-Element ist das referenzierte Elemente unter der Auswahl als Link verknüpft, dort kann es bearbeitet werden und in der Breadcrumb (rechts oben) ist dann der Pfad zur Seite ersichtlich.
