### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#88]
Text, der in den Editor reinkopiert wird, sollte - wie jetzt auch - komplett von allen Formatierungen befreit werden

**Comment by leitgab** [comment]
Hab den erlaubten Content eingeschränkt - passt es so?

**Comment by verenamaidl** [comment]
Schaut nicht übel aus!

Es ist bei den Stilen der Stil für <ul class="link-list">
abhanden gekommen. Da wird die Aufzählung einfach rechtsbündig angesetzt.
Ist z.B. auf PID 8223 beim Text ID 43261 in Verwendung

**Comment by verenamaidl** [comment]
Bitte die beiden "Einzugsmöglichkeiten" aktivieren (Einzug erhöhen/verringern) 
![icons-einzug](https://user-images.githubusercontent.com/72002887/111631190-679bd280-87f3-11eb-8468-1eba050483a6.png)

**Comment by verenamaidl** [comment]
Bitte die beiden Einzugsmöglichkeiten (Einzug erhöhen /verringern aktivieren
![icons-einzug](https://user-images.githubusercontent.com/72002887/111631338-9023cc80-87f3-11eb-9677-6f05daad4462.png)

**Comment by leitgab** [comment]
@verenamaidl List-Item dessen Einzug erhöht/verringert werden soll ist ausgewählt? Bei mir funktioniert es erwartungsgemäß.

**Comment by verenamaidl** [comment]
Sorry - mein Fehler - ich dachte analog zum alten Editor ginge auch ein "normaler" Einzug  - da ist aber scheinbar eine Klasse "indent" definiert. Lass ma es einstweilen so.
