### ISSUE TITLE
weichen Zeilenumbruch in den Überschriften zulassen 

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#89]
Wir hatten das schon: wenn im Headline-Feld ein weicher Zeilenumbruch gesetzt wird, dann muss der Zeilenumbruch auch angezeigt werden
z.B. https://typo3-migration.medunigraz.at/postgraduate-school

**Comment by rubikon-dev** [comment]
Es geht hier um das Standard Typo3 Element Header, dieses Element ist nicht von uns und zusätzlich sind bei unserem Default Header Element die headline einzeilig definiert.
Das wurde am typo3-migration.medunigraz.at System "überschrieben" (Anscheinend global für jedes Input Element das "header" verwendet).

**Comment by verenamaidl** [comment]
In der Headline im Default Header ist der weiche Zeilenumbruch nicht möglich:
siehe https://typo3-migration.medunigraz.at/humanmedizin/lehrveranstaltungen/3-studienabschnitt (PID 9410)

**Comment by verenamaidl** [comment]
Könntest du das bitte wieder aktivieren?

**Comment by leitgab** [comment]
@verenamaidl Bei welchem Element funktioniert es nicht? Habe es soeben beim Header-Only-Element probiert.

**Comment by leitgab** [comment]
Funktioniert nun auch für das Element "Default Header".

Lt. Code besteht vermutlich für folgende Elemente noch das selbe Problem:

- AccordionElement
- HomeSliderElement
- ImageTilesElement
- Link
- LinkButton

Bitte um Info, falls auch diese anzupassen sind.

**Comment by verenamaidl** [comment]
Geht leider schon wieder nicht ... z.B. PID 9410, 8146

**Comment by leitgab** [comment]
War vermutlich nur eine lokale Änderung und noch nicht ins Repository committed und wurde dann beim Wechsel zwischen den Branches/Versionen überschrieben. Ist jetzt im master-Branch committed.
