### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#9]
Info zum Footer, Mail von SH, 9.10. - kannst das nur du eintragen oder find ich das auch irgendwo?

Footer:
> ======
> 
> Constants.ts:
> 
> const.footerNavId = 141
> const.footerOrientationNavId = 142
> const.footerContentIds {
>    de = 160
>    en = 161
> }
> 
> footerNavId: Daraus wird das Footer Menü gebaut. Die Trenner werden verwendet um eine neue Spalte zu beginnen. Es sind 4 Spalten erlaubt.
> Die Icons (z.B. Instagram) werden im Backend befüllt (Resources der Seite/ des Links). Verwendete Icons sind im ZIP File.
> [cid:image001.png@01D69D9D.0492E390][cid:image002.png@01D69D9D.0492E390]
> 
> [cid:image003.png@01D69D9D.0492E390]
> 
> footerOrientationNavId: Definiert Anfahrtsplan/Lageplan (Laut Design 2 / Platz ist begrenzt)
> 
> [cid:image004.png@01D69D9D.0492E390][cid:image005.png@01D69D9D.0492E390]
> 
> footerContentIds: Die beiden Content Ids die die Kontaktdaten im Footer beinhalten.
> Es gibt dafür das eigene CE Default, welches für globale Texte verwendet werden soll.
> Dieses bitte nicht auf "normalen" Seiten verwenden.
> 
> [cid:image006.png@01D69D9D.0492E390][cid:image007.png@01D69D9D.0492E390]
>

**Comment by verenamaidl** [comment]
Könntest du dir den Footer nochmals anschauen? 
Vor allem die Adressen auf deutsch und englisch?

**Comment by fladi** [comment]
Ich habe die Frage per Mail an @rubikon-dev gestellt.

**Comment by fladi** [comment]
@rubikon-dev : Ich habe noch eine Frage zum Footer, wie sind die de und en CEs hier zu verwenden:

const.footerContentIds {
    de = 160
    en = 161
}

Derzeit werden beide gleichzeitig angezeigt, aber ich denke, das soll nicht so sein und es sollte nur das CE der aktuellen Sprache angezeigt werden?

**Comment by rubikon-dev** [comment]
Wo befinden sich die CEs für den Footer?

Wir vermuten das beide CEs die Sprache Deutsch habe.
Die englische Version sollte eine Übersetzung des deutschen CEs sein.

**Comment by verenamaidl** [comment]
Danke für die Info!
Jetzt sollte die Adresse halt nur mehr so angezeigt werden, wie im Design-File ... der Adress-Textblock also oben bündig mit den Strichen der Links rechts

**Comment by shaselwanter** [comment]
@verenamaidl @fladi 
Es wird das falsche CE verwendet (Text). Wie auch im Issue ganz oben steht soll das CE Default verwendet werden das speziell für globale Texte ist

**Comment by verenamaidl** [comment]
Wie schon mehrfach gemeldet: es gibt KEIN CE Default -

**Comment by rubikon-dev** [comment]
Das liegt wahrscheinlich am verwendetet Backend Layout der Seite. Das CE Default ist auf "normalen" Seiten nicht verfügbar.
Wenn man z.B. das Backend Layout "None" auswählt sind alle CEs verfügbar. Unter anderem auch das  CE Default (siehe Screenshot).

![grafik](https://user-images.githubusercontent.com/68015247/98542347-0f772180-2291-11eb-97eb-307dbe4ce152.png)
