### ISSUE TITLE
Backend Layout "Home": nicht alle CEs zur Verfügung

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#93]
es fehlen beim Backend Layout "Home" einige der CEs vom Typical page content, Plugins und Special elements gibt es als Reiter gar nicht.
Ist das bei dir richtig? Sonst bitte weitergeben!

**Comment by leitgab** [comment]
Auf "Home" sind nun auch die Standard-Content Elemente von "Default" verfügbar.
