### ISSUE TITLE
Anker auf englische CEs

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#95]
Auf https://typo3-migration.medunigraz.at/en/med-campus-graz (PID 8407) 
wird im 1. Offer im 4. Element (ART) auf ein CE weiter unten verlinkt.

Beim Übersetzen wird die deutsche ID genommen:
https://typo3-migration.medunigraz.at/en/med-campus-graz#c42097
- die geht aber nicht
[bei unserer jetzigen Typo3-Version muss auch im englischen die deutsche CE-ID genommen werden]

Man kann im englischen CE den Link aber auch nicht ändern, weil in der CE Auswahl NUR DIE DEUTSCHEN CEs aufgelistet werden - und händisch kann man auch nicht https://typo3-migration.medunigraz.at/en/med-campus-graz#c47466  oder t3://page?uid=8407#c47466
eintragen

Soweit so verwirrend ...

**Comment by leitgab** [comment]
Ich habe die Sprachkonfiguration angepasst, somit sollten Sprungmarken analog zur alten Version funktionieren.
