### ISSUE TITLE
CE Text

### ISSUE THREAD

**Issue by verenamaidl** [medunigraz/typo3_mug_internet_design#98]
Die Headline ist jetzt eine H3 - warum auf einmal????
Wir haben diese Überschrift eigentlich nur dann im Einsatz, wenn sie entsprechend größer sein muss - wenn wir für den Text eine kleinere Überschrift brauchen, dann gehen wir eh über den Editor.

zB. https://typo3-migration.medunigraz.at/postgraduate-school/diagnostik-pflege-therapie/sonderausbildung-in-der-anaesthesiepflege

Die beiden Überschriften 
- Sonderausbildung in der Anästhesiepflege
- Spezielle Zusatzausbildung in der Anästhesiepflege
- sollen hier eindeutig Bereiche trennen

**Comment by shaselwanter** [comment]
@verenamaidl 
haben wir auf Wunsch wieder verändet zu: 
H2 und nur beim Bild-Text-Element eine H3
